# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2056537d0149e60bed8ed5d6ab6f9dbdebf57ea1ca3a72ee9279b9bc71b3b64a2e40fca7a58ceb4ccd12249f1e72b0bda09a6dcb976cdff8b5da7164bf42033

test:
  secret_key_base: f81ca58cf57688d15a418a9c02c2884eadb1bf43d5e44578b9df31e88acd993e4b5943e9a1df05eb7c57e22465a60e1d3e1b05b39326605f9ffbc17283567bde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
